// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bawhwfhpfhfbajtykopj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhd2h3ZmhwZmhmYmFqdHlrb3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzY5ODgsImV4cCI6MjA2ODg1Mjk4OH0.YK4v2sddSYgDNXRExblzFg8lxlFT6LfLm51_ukSHz9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});